### ISSUE TITLE
Translation delay

### ISSUE THREAD

**Issue by hauck2** [NightlyRevenger/TataruHelper#38]
Sorry for my English

When talking to some npc, the translation doesn't happen, the previous translation only happens when you go to the next one.

**Comment by xDarkOne** [comment]
It's problem after the last patch. We will fix it as soon as possible

**Comment by RockBarsik** [comment]
The problem is because in new patch, NPC Dialogue in chat window is one phrase late from the cut-scene dialogue. It's not a Tataru problem. I was read in squre enix forum about this.
https://forum.square-enix.com/ffxiv/threads/451596-NPC-dialogue-does-not-enter-the-chat-immediately?p=5768206#post5768206

**Comment by hauck2** [comment]
Problem solved
